/* Shared plan state: one week per signed-in user. Sessions/meals come from
   the user's AI plan (ai_plans table, generated by the planner Edge Function)
   with a deterministic fallback week; completion state lives in Supabase
   (plan_days) through the data layer, mirroring locally for offline. */

import React, {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useRef,
  useState,
} from 'react';

import { buildWeek, PlanDay, PlanDayDone } from './planData';
import { clearWeekProgress, fetchWeekDone, saveDayProgress } from './data';
import { applyPlanToWeek, fetchStoredPlan, generateAiPlan, StoredPlan } from './aiPlan';
import { useAuth } from './auth';

type PlanStore = {
  days: PlanDay[];
  todayIdx: number;
  offline: boolean;
  /** True while the planner Edge Function is generating a fresh plan. */
  generating: boolean;
  /** True when the displayed week comes from the AI planner. */
  aiPlan: boolean;
  /** (Re)generate the plan with the AI planner; applies it on success. */
  regenerate: (goal?: string) => Promise<{ ok: boolean; error?: string }>;
  toggleWorkout: (dayId: string) => Promise<void>;
  toggleExercise: (dayId: string, idx: number) => Promise<void>;
  toggleSet: (dayId: string, exerciseIdx: number, setIdx: number) => Promise<void>;
  toggleMeal: (dayId: string, slot: string) => Promise<void>;
};

const Ctx = createContext<PlanStore | null>(null);

function mergeDone(base: PlanDayDone, patch?: Partial<PlanDayDone>): PlanDayDone {
  if (!patch) return base;
  return {
    workout: patch.workout ?? base.workout,
    exercises: patch.exercises ?? base.exercises,
    meals: patch.meals ?? base.meals,
  };
}

export function PlanProvider({ children }: { children: React.ReactNode }) {
  const [baseDays, setBaseDays] = useState<PlanDay[]>(() => buildWeek());
  const [aiPlan, setAiPlan] = useState<StoredPlan | null>(null);
  const [generating, setGenerating] = useState(false);
  const [offline, setOffline] = useState(false);
  const { userId, session, refreshProfile } = useAuth();
  const nextDoneRef = useRef<PlanDayDone | null>(null);

  // Load the stored AI plan + saved completion state for this user.
  useEffect(() => {
    let alive = true;
    const start = baseDays[0]?.id;
    const end = baseDays[6]?.id;
    if (!userId || !start || !end) return;

    fetchStoredPlan(userId).then((plan) => {
      if (alive) setAiPlan(plan);
    });

    fetchWeekDone(userId, start, end).then(({ done, offline: off }) => {
      if (!alive) return;
      setOffline(off);
      const saved = done ?? {};
      setBaseDays((prev) =>
        prev.map((d) => (saved[d.id] ? { ...d, done: mergeDone(d.done, saved[d.id]) } : d)),
      );
    });

    return () => {
      alive = false;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [userId]);

  const days = useMemo(
    () => (aiPlan ? applyPlanToWeek(aiPlan, baseDays) : baseDays),
    [aiPlan, baseDays],
  );

  const regenerate = useCallback(
    async (goal?: string): Promise<{ ok: boolean; error?: string }> => {
      if (!session) return { ok: false, error: 'Sign in to generate a plan' };
      setGenerating(true);
      try {
        const plan = await generateAiPlan(goal);
        // A new plan replaces the old one: old checkmarks don't map onto the
        // new exercises/meals, so the week starts with a clean checklist.
        setBaseDays((prev) => prev.map((d) => ({ ...d, done: { workout: false, exercises: [], meals: [] } })));
        await clearWeekProgress(userId!, baseDays[0]?.id ?? '', baseDays[6]?.id ?? '');
        setAiPlan(plan); // the days memo applies it to the week immediately
        // The planner mirrors kcal/water targets onto the profile; pick them up
        // so the Today ring and water card show the new targets right away.
        void refreshProfile();
        return { ok: true };
      } catch (e) {
        return { ok: false, error: String((e as Error)?.message ?? e) };
      } finally {
        setGenerating(false);
      }
    },
    [session, userId, refreshProfile, baseDays],
  );

  const patchDay = useCallback(
    async (dayId: string, patch: Parameters<typeof saveDayProgress>[2]) => {
      setBaseDays((prev) =>
        prev.map((d): PlanDay => {
          if (d.id !== dayId) return d;
          const next: PlanDayDone = {
            workout: patch.workout ?? d.done.workout,
            exercises: patch.exercises ?? d.done.exercises,
            meals: patch.meals ?? d.done.meals,
          };
          nextDoneRef.current = next;
          return { ...d, done: next };
        }),
      );
      const nextDone = nextDoneRef.current;
      if (userId && nextDone) {
        await saveDayProgress(userId, dayId, {
          workout: nextDone.workout,
          exercises: nextDone.exercises,
          meals: nextDone.meals,
        });
      }
    },
    [userId],
  );

  const toggleWorkout = useCallback(
    async (dayId: string) => {
      const d = days.find((x) => x.id === dayId);
      if (!d || d.session.kind !== 'workout') return;
      const on = !d.done.workout;
      await patchDay(dayId, {
        workout: on,
        exercises: on
          ? d.session.exercises.map((ex) => Array.from({ length: ex.sets }, (_, s) => s))
          : [],
      });
    },
    [days, patchDay],
  );

  const toggleExercise = useCallback(
    async (dayId: string, idx: number) => {
      const d = days.find((x) => x.id === dayId);
      if (!d || d.session.kind !== 'workout') return;
      const done = [...d.done.exercises];
      const ex = d.session.exercises[idx];
      const all = Array.isArray(done[idx]) && done[idx].length === ex.sets;
      done[idx] = all ? [] : Array.from({ length: ex.sets }, (_, s) => s);
      const allDone = d.session.exercises.every((e, i) => (done[i] ?? []).length === e.sets);
      await patchDay(dayId, { exercises: done, workout: allDone });
    },
    [days, patchDay],
  );

  const toggleSet = useCallback(
    async (dayId: string, exerciseIdx: number, setIdx: number) => {
      const d = days.find((x) => x.id === dayId);
      if (!d || d.session.kind !== 'workout') return;
      const done = d.done.exercises.map((r) => [...(r ?? [])]);
      while (done.length <= exerciseIdx) done.push([]);
      const row = done[exerciseIdx];
      const has = row.includes(setIdx);
      done[exerciseIdx] = has ? row.filter((x) => x !== setIdx) : [...row, setIdx].sort((a, b) => a - b);
      const allDone = d.session.exercises.every(
        (e, i) => (done[i] ?? []).filter((x) => x < e.sets).length === e.sets,
      );
      await patchDay(dayId, { exercises: done, workout: allDone });
    },
    [days, patchDay],
  );

  const toggleMeal = useCallback(
    async (dayId: string, slot: string) => {
      const d = days.find((x) => x.id === dayId);
      if (!d) return;
      const set = new Set(d.done.meals);
      if (set.has(slot)) set.delete(slot);
      else set.add(slot);
      await patchDay(dayId, { meals: [...set] });
    },
    [days, patchDay],
  );

  const todayIdx = useMemo(() => (new Date().getDay() + 6) % 7, []);
  const value = useMemo<PlanStore>(
    () => ({ days, todayIdx, offline, generating, aiPlan: !!aiPlan, regenerate, toggleWorkout, toggleExercise, toggleSet, toggleMeal }),
    [days, todayIdx, offline, generating, aiPlan, regenerate, toggleWorkout, toggleExercise, toggleSet, toggleMeal],
  );

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function usePlan(): PlanStore {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error('usePlan must be used inside <PlanProvider>');
  return ctx;
}
