/* Shared plan state for the signed-in person (or device-only identity).

   - The week shown is the Mon..Sun week containing TODAY, and today rolls
     over at midnight and whenever the app comes back to the foreground.
   - Sessions/meals come from the active AI plan (ai_plans, generated by the
     planner Edge Function) or the built-in rules week.
   - Completion rows (`history`) cover the past year plus this week, so the
     streak and the Progress tab follow real history across weeks, judged
     against the plan actually in use (`schedule`).
   - Every toggle computes the next state from the LATEST state (not a stale
     render), updates the screen at once, and saves the full intended row.
     Saves for one day run strictly in order (data layer), so rapid taps
     can't race or save stale data. */

import React, { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState } from 'react';

import { addDays, isoDay, mondayIndex, parseDay, weekStartId } from './lib/dates';
import { isCloudUser } from './lib/cloud';
import { useToday } from './lib/useToday';
import {
  composeWeek,
  daysToClearOnRegenerate,
  DoneMap,
  DoneRow,
  EMPTY_DONE,
  PlanDay,
  scheduleOf,
  StoredPlan,
  WeekSchedule,
} from './planData';
import { clearDaysProgress, fetchDoneRange, saveDayProgress } from './data';
import { fetchStoredPlan, generateAiPlan } from './aiPlan';
import { currentStreak, STREAK_HORIZON_DAYS } from './streak';
import { useAuth } from './auth';

/** 'local': device-only identity, nothing syncs. 'offline': an account
    whose server couldn't be reached; changes upload when it's back.
    'synced': the last read or write reached the server. */
export type SyncState = 'local' | 'offline' | 'synced';

type PlanStore = {
  days: PlanDay[];
  /** Index of today in `days` (0 = Monday). Rolls over at midnight. */
  todayIdx: number;
  /** Today's id, yyyy-mm-dd (local day). */
  todayId: string;
  /** True unless the last read/write reached the server (see syncState). */
  offline: boolean;
  syncState: SyncState;
  /** True while the planner Edge Function is generating a fresh plan. */
  generating: boolean;
  /** True when the displayed week comes from the AI planner. */
  aiPlan: boolean;
  /** Training weekdays of the plan in use, Monday first. */
  schedule: WeekSchedule;
  /** Completion rows by day id: the past year plus this week. */
  history: DoneMap;
  /** True once `history` has loaded from the server or the device. */
  historyLoaded: boolean;
  /** Current workout streak across weeks. Same number Progress shows. */
  streak: number;
  /** (Re)generate the plan with the AI planner; applies it on success.
      Past days (and a finished today) keep their checkmarks. */
  regenerate: (goal?: string) => Promise<{ ok: boolean; error?: string }>;
  toggleWorkout: (dayId: string) => Promise<void>;
  /** Idempotent: mark a day's workout done (all sets) or not done. */
  setWorkoutDone: (dayId: string, done: boolean) => Promise<void>;
  toggleExercise: (dayId: string, idx: number) => Promise<void>;
  toggleSet: (dayId: string, exerciseIdx: number, setIdx: number) => Promise<void>;
  toggleMeal: (dayId: string, slot: string) => Promise<void>;
};

const Ctx = createContext<PlanStore | null>(null);

function allSets(day: PlanDay): number[][] {
  return day.session.kind === 'workout'
    ? day.session.exercises.map((ex) => Array.from({ length: ex.sets }, (_, s) => s))
    : [];
}

function everySetDone(day: PlanDay, exercises: number[][]): boolean {
  if (day.session.kind !== 'workout' || !day.session.exercises.length) return false;
  return day.session.exercises.every((e, i) => (exercises[i] ?? []).filter((x) => x < e.sets).length === e.sets);
}

export function PlanProvider({ children }: { children: React.ReactNode }) {
  const { userId, session, refreshProfile } = useAuth();
  const today = useToday();
  const todayDate = useMemo(() => parseDay(today), [today]);
  const weekStart = weekStartId(todayDate);

  const [aiPlan, setAiPlan] = useState<StoredPlan | null>(null);
  const [done, setDoneState] = useState<DoneMap>({});
  const [historyLoaded, setHistoryLoaded] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [reachedServer, setReachedServer] = useState(true);

  // The latest completion state, readable synchronously by rapid taps.
  const doneRef = useRef<DoneMap>({});
  const commit = useCallback((next: DoneMap) => {
    doneRef.current = next;
    setDoneState(next);
  }, []);
  // Days changed on this device since the last server read started; a
  // read that lands later must not overwrite them.
  const touched = useRef<Set<string>>(new Set());

  // A different person: start from a clean slate, never show someone
  // else's checkmarks or plan.
  useEffect(() => {
    touched.current = new Set();
    commit({});
    setAiPlan(null);
    setHistoryLoaded(false);
    setReachedServer(true);
  }, [userId, commit]);

  // Load the plan and a year of completion history (and again when the week
  // rolls over).
  useEffect(() => {
    if (!userId) return;
    let alive = true;
    touched.current = new Set();

    fetchStoredPlan(userId).then((plan) => {
      if (alive) setAiPlan(plan);
    });

    const from = addDays(weekStart, -STREAK_HORIZON_DAYS);
    const to = addDays(weekStart, 6);
    fetchDoneRange(userId, from, to).then(({ done: saved, offline, local }) => {
      if (!alive) return;
      if (!local) setReachedServer(!offline);
      const next: DoneMap = { ...saved };
      for (const id of touched.current) {
        if (doneRef.current[id]) next[id] = doneRef.current[id];
        else delete next[id];
      }
      commit(next);
      setHistoryLoaded(true);
    });

    return () => {
      alive = false;
    };
  }, [userId, weekStart, commit]);

  const days = useMemo(() => composeWeek(todayDate, aiPlan, done), [todayDate, aiPlan, done]);
  const daysRef = useRef(days);
  daysRef.current = days;

  const schedule = useMemo(() => scheduleOf(days), [days]);
  const streak = useMemo(() => currentStreak(done, schedule, today), [done, schedule, today]);

  /** Apply `compute` to the latest state of one day and save the result. */
  const patchDay = useCallback(
    async (dayId: string, compute: (cur: DoneRow, day: PlanDay) => DoneRow | null) => {
      const day = daysRef.current.find((d) => d.id === dayId);
      if (!day) return;
      const cur = doneRef.current[dayId] ?? EMPTY_DONE;
      const next = compute(cur, day);
      if (!next) return;
      touched.current.add(dayId);
      commit({ ...doneRef.current, [dayId]: next });
      if (!userId) return;
      const ok = await saveDayProgress(userId, dayId, next);
      if (isCloudUser(userId)) setReachedServer(ok);
    },
    [userId, commit],
  );

  const setWorkoutDone = useCallback(
    (dayId: string, on: boolean) =>
      patchDay(dayId, (cur, day) => {
        if (day.session.kind !== 'workout') return null;
        if (cur.workout === on && (!on || everySetDone(day, cur.exercises))) return null;
        return { ...cur, workout: on, exercises: on ? allSets(day) : [] };
      }),
    [patchDay],
  );

  const toggleWorkout = useCallback(
    (dayId: string) =>
      patchDay(dayId, (cur, day) => {
        if (day.session.kind !== 'workout') return null;
        const on = !cur.workout;
        return { ...cur, workout: on, exercises: on ? allSets(day) : [] };
      }),
    [patchDay],
  );

  const toggleExercise = useCallback(
    (dayId: string, idx: number) =>
      patchDay(dayId, (cur, day) => {
        if (day.session.kind !== 'workout') return null;
        const ex = day.session.exercises[idx];
        if (!ex) return null;
        const exercises = day.session.exercises.map((_, i) => [...(cur.exercises[i] ?? [])]);
        const full = exercises[idx].filter((x) => x < ex.sets).length === ex.sets;
        exercises[idx] = full ? [] : Array.from({ length: ex.sets }, (_, s) => s);
        return { ...cur, exercises, workout: everySetDone(day, exercises) };
      }),
    [patchDay],
  );

  const toggleSet = useCallback(
    (dayId: string, exerciseIdx: number, setIdx: number) =>
      patchDay(dayId, (cur, day) => {
        if (day.session.kind !== 'workout') return null;
        const exercises = cur.exercises.map((r) => [...(r ?? [])]);
        while (exercises.length <= exerciseIdx) exercises.push([]);
        const row = exercises[exerciseIdx];
        exercises[exerciseIdx] = row.includes(setIdx)
          ? row.filter((x) => x !== setIdx)
          : [...row, setIdx].sort((a, b) => a - b);
        return { ...cur, exercises, workout: everySetDone(day, exercises) };
      }),
    [patchDay],
  );

  const toggleMeal = useCallback(
    (dayId: string, slot: string) =>
      patchDay(dayId, (cur) => {
        const set = new Set(cur.meals);
        if (set.has(slot)) set.delete(slot);
        else set.add(slot);
        return { ...cur, meals: [...set] };
      }),
    [patchDay],
  );

  const regenerate = useCallback(
    async (goal?: string): Promise<{ ok: boolean; error?: string }> => {
      if (!session || !isCloudUser(userId)) return { ok: false, error: 'Sign in to build a new plan.' };
      setGenerating(true);
      try {
        const plan = await generateAiPlan(goal, userId);
        // Old checkmarks don't map onto new exercises: clear future days
        // (and today, unless its workout is finished). Past days are history.
        const todayNow = isoDay(new Date());
        const clear = daysToClearOnRegenerate(doneRef.current, todayNow);
        if (clear.length) {
          const next = { ...doneRef.current };
          for (const id of clear) {
            delete next[id];
            touched.current.add(id);
          }
          commit(next);
          await clearDaysProgress(userId, clear);
        }
        setAiPlan(plan); // the days memo applies it to the week immediately
        // The planner mirrors kcal/water targets onto the profile; pick them up
        // so the Today ring and water card show the new targets right away.
        void refreshProfile();
        return { ok: true };
      } catch (e) {
        return { ok: false, error: String((e as Error)?.message ?? e) };
      } finally {
        setGenerating(false);
      }
    },
    [session, userId, refreshProfile, commit],
  );

  const syncState: SyncState = !isCloudUser(userId) ? 'local' : reachedServer ? 'synced' : 'offline';
  const todayIdx = mondayIndex(todayDate);

  const value = useMemo<PlanStore>(
    () => ({
      days,
      todayIdx,
      todayId: today,
      offline: syncState !== 'synced',
      syncState,
      generating,
      aiPlan: !!aiPlan,
      schedule,
      history: done,
      historyLoaded,
      streak,
      regenerate,
      toggleWorkout,
      setWorkoutDone,
      toggleExercise,
      toggleSet,
      toggleMeal,
    }),
    [days, todayIdx, today, syncState, generating, aiPlan, schedule, done, historyLoaded, streak, regenerate, toggleWorkout, setWorkoutDone, toggleExercise, toggleSet, toggleMeal],
  );

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}

export function usePlan(): PlanStore {
  const ctx = useContext(Ctx);
  if (!ctx) throw new Error('usePlan must be used inside <PlanProvider>');
  return ctx;
}
