// Generated by scripts/gen-media.mjs. Do not edit by hand.
// AI-generated photos for the meal libraries, keyed by slug(label).
/* eslint-disable */
export const MEAL_IMAGES: Record<string, number> = {};
