import React from 'react';
import { LegalPage } from '@/components';

export default function Terms() {
  return (
    <LegalPage
      title="Terms of service"
      updated="January 2026"
      sections={[
        {
          heading: 'Using VITAL',
          body: 'VITAL provides personalized nutrition and fitness guidance generated by software. You must be at least 16 to create an account, and you are responsible for keeping your credentials secure.',
        },
        {
          heading: 'Not medical advice',
          body: 'VITAL is a wellness product, not a medical service. Its recommendations do not replace advice from a doctor, dietitian or other qualified professional. Consult a healthcare professional before starting a new diet or exercise programme, particularly if you have an existing condition, are pregnant, or take medication.',
        },
        {
          heading: 'Subscription and billing',
          body: 'Access is provided through a $30 monthly subscription billed via the App Store, Google Play or Stripe. Subscriptions renew automatically until cancelled. You can cancel at any time and keep access until the end of the paid period.',
        },
        {
          heading: 'Acceptable use',
          body: 'Do not attempt to disrupt the service, reverse engineer it, or use it to distribute unlawful or harmful content.',
        },
        {
          heading: 'Changes to the service',
          body: 'We may add, change or remove features over time. If a change materially reduces what you have paid for, we will tell you in advance.',
        },
        {
          heading: 'Contact',
          body: 'Questions about these terms can be sent to legal@vital.app.',
        },
      ]}
    />
  );
}
