#!/usr/bin/env node
// Generates the app's media libraries. Runs in GitHub Actions
// (.github/workflows/gen-media.yml), which has open internet; it is safe to
// re-run: files that already exist are kept.
//
//  1. Meal photos: a realistic, AI-generated photo for every meal in the two
//     meal libraries (mobile/src/planData.ts and
//     supabase/functions/_shared/food.ts), made with the free Flux model on
//     Pollinations and saved as 640x640 WebP in mobile/assets/meals/<slug>.webp.
//     Writes mobile/src/data/mealImages.generated.ts (slug -> require()).
//  2. Workout videos: one embeddable YouTube form tutorial per exercise in
//     mobile/src/data/exercises.ts, preferring well-known coaching channels and
//     videos under 10 minutes. Writes mobile/src/data/exerciseVideos.generated.json.
//
// Needs `sharp` (installed by the workflow). Flags: --meals-only, --videos-only,
// --force (regenerate even when a file exists).

import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const args = new Set(process.argv.slice(2));
const FORCE = args.has('--force');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const START = Date.now();
const MEAL_BUDGET_MS = 40 * 60_000; // stop starting new meal images after this
const VIDEO_BUDGET_MS = 65 * 60_000; // stop searching videos after this (from start)
const LOG_FILE = path.join(ROOT, '.github/gen-media-last-run.log');
const logLines = [];
function log(...a) {
  const line = `[${((Date.now() - START) / 1000).toFixed(0)}s] ${a.join(' ')}`;
  console.log(line);
  logLines.push(line);
  try { fs.writeFileSync(LOG_FILE, logLines.join('\n') + '\n'); } catch {}
}

/** Must match mobile/src/lib/slug.ts. */
export function slug(label) {
  return label
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// ─────────────────────────────── meals ───────────────────────────────

function mealLabels() {
  const files = ['mobile/src/planData.ts', 'supabase/functions/_shared/food.ts'];
  const labels = new Set();
  for (const f of files) {
    const src = fs.readFileSync(path.join(ROOT, f), 'utf8');
    const re = /\bm\(\s*'(?:Breakfast|Lunch|Dinner|Snack)',\s*(['"])(.+?)\1/g;
    let m;
    while ((m = re.exec(src))) labels.add(m[2]);
    // The original built-in week (v1) labels.
    const re2 = /label: '([^']+)'/g;
    while ((m = re2.exec(src))) labels.add(m[1]);
  }
  return [...labels];
}

function mealPrompt(label) {
  return [
    `Professional food photograph of ${label}`,
    'home-style Lebanese and Mediterranean cooking, generous realistic portion',
    'served on a matte ceramic plate on a dark stone table',
    'soft natural window light, 45 degree angle, shallow depth of field',
    'photorealistic, appetizing, sharp focus, true-to-life colors',
    'no text, no logo, no watermark, no people, no hands',
  ].join(', ');
}

async function fetchWithRetry(url, opts = {}, tries = 2, timeoutMs = 90_000) {
  let last;
  for (let i = 0; i < tries; i++) {
    try {
      const r = await fetch(url, { ...opts, signal: AbortSignal.timeout(timeoutMs) });
      if (r.ok) return r;
      const body = (await r.text().catch(() => '')).slice(0, 200).replace(/\s+/g, ' ');
      last = new Error(`HTTP ${r.status} ${body}`);
      if (r.status === 429) await sleep(15_000 * (i + 1));
      else await sleep(4_000 * (i + 1));
    } catch (e) {
      last = e;
      await sleep(5_000 * (i + 1));
    }
  }
  throw last;
}

async function genMeals() {
  const { default: sharp } = await import('sharp');
  const dir = path.join(ROOT, 'mobile/assets/meals');
  fs.mkdirSync(dir, { recursive: true });
  const labels = mealLabels();
  log(`meals: ${labels.length} labels`);
  const done = [];
  const writeIndex = () => {
    const lines = [...done]
      .sort()
      .map((s) => `  '${s}': require('../../assets/meals/${s}.webp'),`)
      .join('\n');
    const ts =
      `// Generated by scripts/gen-media.mjs. Do not edit by hand.\n` +
      `// AI-generated photos (Flux) for the meal libraries, keyed by slug(label).\n` +
      `/* eslint-disable */\n` +
      `export const MEAL_IMAGES: Record<string, number> = {\n${lines}\n};\n`;
    fs.writeFileSync(path.join(ROOT, 'mobile/src/data/mealImages.generated.ts'), ts);
  };
  for (const label of labels) {
    const s = slug(label);
    const out = path.join(dir, `${s}.webp`);
    if (fs.existsSync(out) && !FORCE) {
      done.push(s);
      continue;
    }
    if (Date.now() - START > MEAL_BUDGET_MS) {
      log('meals: time budget reached, the rest are left for the next run');
      break;
    }
    const seed = parseInt(crypto.createHash('sha1').update(s).digest('hex').slice(0, 8), 16) % 1_000_000;
    const url =
      `https://image.pollinations.ai/prompt/${encodeURIComponent(mealPrompt(label))}` +
      `?width=1024&height=1024&seed=${seed}&model=flux&nologo=true&private=true&enhance=false`;
    try {
      const t0 = Date.now();
      const r = await fetchWithRetry(url, { headers: { 'User-Agent': 'BUILT-media-generator/1.0' } });
      const type = r.headers.get('content-type') || '';
      const buf = Buffer.from(await r.arrayBuffer());
      if (!type.startsWith('image/')) throw new Error(`not an image (${type}): ${buf.toString('utf8', 0, 160)}`);
      await sharp(buf).resize(640, 640, { fit: 'cover' }).webp({ quality: 74 }).toFile(out);
      done.push(s);
      writeIndex();
      log(`  ok   ${s} (${((Date.now() - t0) / 1000).toFixed(0)}s, ${buf.length} bytes)`);
    } catch (e) {
      log(`  FAIL ${s}: ${e.message}`);
    }
    await sleep(3_000); // the free tier allows about one request at a time
  }
  writeIndex();
  log(`meals: ${done.length}/${labels.length} images`);
}

// ─────────────────────────────── videos ───────────────────────────────

const TRUSTED = [
  'renaissance periodization', 'jeff nippard', 'scottherman', 'scott herman', 'buff dudes',
  'athlean-x', 'squat university', 'nuffield health', 'howcast', 'mayo clinic',
  'bodybuilding.com', "men's health", "women's health", 'calisthenicmovement',
  'live lean tv', 'mind pump', 'alan thrall', 'jeremy ethier', 'e3 rehab', 'strengthlog',
  'muscle & strength', 'muscleandstrength', 'national academy of sports medicine', 'nasm',
  'ace fitness', 'american council on exercise', 'well+good', 'popsugar fitness',
  'garage strength', 'barbell medicine', 'mark rippetoe', 'starting strength',
];

function exerciseList() {
  const src = fs.readFileSync(path.join(ROOT, 'mobile/src/data/exercises.ts'), 'utf8');
  const re = /\bx\(\s*'([a-z0-9_]+)',\s*'([^']+)'/g;
  const out = [];
  let m;
  while ((m = re.exec(src))) out.push({ id: m[1], name: m[2] });
  return out;
}

function seconds(t) {
  if (!t) return null;
  return t.split(':').reduce((a, n) => a * 60 + Number(n), 0);
}

function* walk(o) {
  if (!o || typeof o !== 'object') return;
  if (o.videoRenderer) yield o.videoRenderer;
  for (const v of Array.isArray(o) ? o : Object.values(o)) yield* walk(v);
}

async function searchYouTube(q) {
  const url = `https://www.youtube.com/results?search_query=${encodeURIComponent(q)}&hl=en&gl=US`;
  const r = await fetchWithRetry(url, {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36',
      'Accept-Language': 'en-US,en;q=0.9',
      Cookie: 'CONSENT=YES+1; SOCS=CAI',
    },
  }, 2, 30_000);
  const html = await r.text();
  const m = html.match(/var ytInitialData = (\{.*?\});<\/script>/s);
  if (!m) return [];
  const data = JSON.parse(m[1]);
  const out = [];
  for (const v of walk(data)) {
    const id = v.videoId;
    const title = v.title?.runs?.map((x) => x.text).join('') ?? '';
    const channel = v.ownerText?.runs?.[0]?.text ?? '';
    const length = seconds(v.lengthText?.simpleText);
    if (id && !out.some((o) => o.videoId === id)) out.push({ videoId: id, title, channel, seconds: length });
    if (out.length >= 12) break;
  }
  return out;
}

async function embeddable(id) {
  try {
    const r = await fetch(`https://www.youtube.com/oembed?url=${encodeURIComponent(`https://www.youtube.com/watch?v=${id}`)}&format=json`, { signal: AbortSignal.timeout(20_000) });
    return r.ok;
  } catch {
    return false;
  }
}

async function genVideos() {
  const file = path.join(ROOT, 'mobile/src/data/exerciseVideos.generated.json');
  const prev = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : {};
  const list = exerciseList();
  log(`videos: ${list.length} exercises`);
  const out = {};
  for (const ex of list) {
    if (prev[ex.id] && !FORCE) {
      out[ex.id] = prev[ex.id];
      continue;
    }
    if (Date.now() - START > VIDEO_BUDGET_MS) {
      log('videos: time budget reached, the rest are left for the next run');
      break;
    }
    try {
      const results = (await searchYouTube(`${ex.name} exercise proper form tutorial`))
        .filter((v) => v.seconds != null && v.seconds >= 25 && v.seconds <= 600);
      const score = (v) =>
        (TRUSTED.some((t) => v.channel.toLowerCase().includes(t)) ? 10 : 0) +
        (/how to|form|tutorial|technique/i.test(v.title) ? 2 : 0) -
        results.indexOf(v) * 0.3;
      const ranked = [...results].sort((a, b) => score(b) - score(a));
      let pick = null;
      for (const v of ranked.slice(0, 6)) {
        if (await embeddable(v.videoId)) {
          pick = v;
          break;
        }
      }
      if (pick) {
        out[ex.id] = { videoId: pick.videoId, title: pick.title.slice(0, 120), channel: pick.channel.slice(0, 60), seconds: pick.seconds };
        log(`  ok   ${ex.id}: ${pick.channel} | ${pick.title.slice(0, 60)}`);
      } else {
        log(`  none ${ex.id} (${results.length} results)`);
      }
    } catch (e) {
      log(`  FAIL ${ex.id}: ${e.message}`);
    }
    fs.writeFileSync(file, JSON.stringify(out, null, 2) + '\n');
    await sleep(1_500);
  }
  fs.writeFileSync(file, JSON.stringify(out, null, 2) + '\n');
  log(`videos: ${Object.keys(out).length}/${list.length} found`);
}

if (!args.has('--videos-only')) await genMeals();
if (!args.has('--meals-only')) await genVideos();
